name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools for UI
      run: sudo apt-get update && sudo apt-get install -y build-essential python3 g++ make

    - name: Install dependencies for UI
      run: |
        cd ui
        npm install

    - name: Build the UI with Vite
      run: |
        cd ui
        npm run build

    - name: Install Python dependencies for Server
      run: |
        pip install -r requirements.txt

    - name: Deploy to EC2
      run: |
        mkdir -p ~/.ssh
    
        echo "$EC2_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
        ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
    
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$EC2_USER@$EC2_HOST" << 'EOF'
          cd /home/$EC2_USER/app/ui
          npm install
          npm run build
          cd /home/$EC2_USER/app/server
          pip install -r requirements.txt
        EOF
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}



