name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      run: |
        mkdir -p ~/.ssh
    
        echo "$EC2_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
        ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
    
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "ubuntu@$EC2_HOST" << "EOF"
          cd /home/ubuntu/AirAlarmsApp
          git pull
          cd /home/ubuntu/AirAlarmsApp/ui
          npm install
          npx tsc -b && vite build
          cd /home/ubuntu/AirAlarmsApp
          . .venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart airalarmsapp.service
        EOF
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}



