name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install build tools for UI (Node.js)
    - name: Install build tools for UI
      run: sudo apt-get update && sudo apt-get install -y build-essential python3 g++ make

    # Install dependencies for UI
    - name: Install dependencies for UI
      run: |
        cd ui
        npm install

    # Build the Vite React app
    - name: Build the UI with Vite
      run: |
        cd ui
        npm run build

    # Install Python dependencies for the server
    - name: Install Python dependencies for Server
      run: |
        cd app
        pip install -r requirements.txt

    # Deploy to EC2 (example)
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/app/ui
          npm install
          npm run build
          cd /home/${{ secrets.EC2_USER }}/app/server
          pip install -r requirements.txt
          uvicorn main:app --host 0.0.0.0 --port 8000
        EOF
